# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41ec58cfb0125b83d2b6c177652cee1114b006b9393ebbcf942d0d8a7c573d64fb1d29a44f0680fb0678b982356aaec60d7f251fae44c8f1dc617ea88bc4dbf

test:
  secret_key_base: 0cf10997c3068e164fb1770e694cecebd669f80f473668bc66149ef9a951d695ef855568835edcafda8ecb24b6feb71498934817f7913eb65efce5b23fd9ca1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
